### ISSUE TITLE
Does wasapi-rs require nightly?

### ISSUE THREAD

**Issue by SecondFlight** [HEnquist/wasapi-rs#11]
I've cloned this repository and run `cargo run --exapmle playsine`. Doing this gave the following error:

```
   ...
   Compiling windows v0.33.0
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\qbgee\.cargo\registry\src\github.com-1ecc6299db9ec823\windows-0.33.0\src\lib.rs:5:36
  |
5 | #![cfg_attr(feature = "implement", feature(const_fn_fn_ptr_basics))]
  |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\qbgee\.cargo\registry\src\github.com-1ecc6299db9ec823\windows-0.33.0\src\lib.rs:6:36
  |
6 | #![cfg_attr(feature = "implement", feature(const_fn_trait_bound))]
  |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `windows` due to 2 previous errors
```

Is `wasapi-rs` meant to require unstable/nightly, or might this be an error on my side?

I'm using Rust stable v1.59.0.

**Comment by HEnquist** [comment]
The latest versions of the windows crate requires nightly if the optional feature for implementing com interfaces is enabled. Since wasapi-rs uses that it means nightly is required here too. They are doing their best to get the things needed stabilized, so expect this to change soon.
See https://github.com/microsoft/windows-rs/issues/1523

**Comment by SecondFlight** [comment]
Thanks for the reply and the issue link! I'll add that issue to my watch list.

**Comment by HEnquist** [comment]
https://github.com/HEnquist/wasapi-rs/pull/12
With windows-rs 0.34 the stable compiler can be used as soon as rustc 1.61 is released. Nightly is still needed until then.
