### ISSUE TITLE
How to play recorded.raw file?

### ISSUE THREAD

**Issue by LuckyHookin** [HEnquist/wasapi-rs#17]
I'm sorry. I can't convert this file to MP3, can you give some hints?

**Comment by HEnquist** [comment]
From the record example? It stores the raw data without any header. You can import it in any audio editor that supports importing raw data. Audacity works fine for example. Select 32-bit little-endian  float and 2 channels.

**Comment by LuckyHookin** [comment]
@HEnquist Thanks for the reply! But Render mode seems to be a bit problematic, sometimes it speeds up and there is a current sound.

https://user-images.githubusercontent.com/45350455/204091427-b09fb30a-039b-4f08-9f76-aad8a7fdceb7.mp4

**Comment by HEnquist** [comment]
Did you run the example with `cargo run --example --release`? If not, please try that.

**Comment by LuckyHookin** [comment]
I found that record.rs is not using the same output device as the music player, which is not a bad situation when they are using the same output device.
Thanks!
