### ISSUE TITLE
Add `fn deinitialize()` utilizing `CoUninitialize`

### ISSUE THREAD

**Issue by rosingrind** [HEnquist/wasapi-rs#19]
As stated in [docs](https://learn.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-coinitializeex#remarks):

> To close the COM library gracefully on a thread, each successful call to [CoInitialize](https://learn.microsoft.com/en-us/windows/desktop/api/objbase/nf-objbase-coinitialize) or [CoInitializeEx](https://learn.microsoft.com/en-us/windows/desktop/api/combaseapi/nf-combaseapi-coinitializeex), including any call that returns S_FALSE, must be balanced by a corresponding call to [CoUninitialize](https://learn.microsoft.com/en-us/windows/desktop/api/combaseapi/nf-combaseapi-couninitialize)

I'm not really familiar with the `wasapi` crate development direction, but I think there should be a function such as `fn deinitialize()` for these safety purposes. What's your opinion?

https://github.com/HEnquist/wasapi-rs/blob/bf15059518796e19ee3d8a8e1d6d9fb096d37d7b/src/api.rs#L61-L68

**Comment by HEnquist** [comment]
Thanks, this is a good suggestion. I'll include it in the next version.

**Comment by HEnquist** [comment]
Added in https://github.com/HEnquist/wasapi-rs/commit/2613e9797280ff082f2d786abb2454faf31aab87
