### ISSUE TITLE
Iterator on DeviceCollection

### ISSUE THREAD

**Issue by 3tilley** [HEnquist/wasapi-rs#20]
Hello,

Is there any reason there isn't an iterator on `DeviceCollection`? If not would you object to me adding one?

**Comment by HEnquist** [comment]
No reason, I just haven't needed it (yet) 😀 
PR welcome!

**Comment by 3tilley** [comment]
Do you think it should be on `DeviceCollection` or on a new `DeviceCollectionIter` struct?

**Comment by HEnquist** [comment]
I think this approach in alsa-rs is good:
https://github.com/diwic/alsa-rs/blob/master/src/ctl_int.rs#L24
