### ISSUE TITLE
Set default audio device

### ISSUE THREAD

**Issue by 3tilley** [HEnquist/wasapi-rs#22]
Hello,

This PR isn't raised with any intention of merging, merely to posit a question.

https://github.com/3tilley/wasapi-rs/compare/iterators-pr...3tilley:wasapi-rs:default-device

Please don't worry about the quality of the code above, I'm aware it's a bit of a bombsite I just wanted to achieve an MVP to see what it would take to change the default Audio Device.

In theory, with clean implementation in a formal PR would you be interested in having the (feature-gated?) ability to update the default audio device in this crate? The pros and cons that I can see:
### Pros
* It's immensely useful functionality that doesn't exist in any libraries currently (looking is what brought me to this one)
* This crate contains `get_default` which somewhat begs `set_default`
### Cons
* It relies on an undocumented COM API to achieve this (you'll have to believe me that in all the research I've done this is the only way I can find to do it)
* It's an unstable API, different GUIDs are required for different versions of Windows
* It doesn't use wasapi, which the cratename suggests is purpose of this crate

The alternative would be I just make a separate crate or just inline it into my application. This would be worse from the PoV of dependency spread and my inexperience of being a maintainer, but may be a better separation of concerns.

I won't be offended either way, just interested in your opinion!

Max

**Comment by HEnquist** [comment]
I must say I'm not very keen on adding support for undocumented APIs. This also falls outside of the scope I had envisioned for this crate, which is just what you need for recording and playback. The Windows APIs are huge and it's tempting to add a little bit of this thing that could be useful, then a little bit of something else. In the end it would be huge and very hard to support and maintain.

I would suggest including this in your own code for now. A future project could be to split it off to its own crate. Then it would make sense to provide more functionality and expose all the methods of the PolicyConfigClient.

**Comment by 3tilley** [comment]
Agree on all fronts, thanks!
