### ISSUE TITLE
Application Specific Audio Loopback

### ISSUE THREAD

**Issue by JohnMitchell04** [HEnquist/wasapi-rs#26]
Hi, thanks to the maintainers of this crate, it was a great help for me in developing a recent side project.

I was wondering if there was any plans to add application specific audio loopback and capture as demonstrated in [this](https://learn.microsoft.com/en-us/samples/microsoft/windows-classic-samples/applicationloopbackaudio-sample/) Win32 classic sample. The sample states functionality is limited to Windows 10 version 20348 or later, however OBS uses it from Windows 10 version 2004 or later.

I would be happy to create and work on a pull request to contribute the necessary code, however I just wanted to check if there was any desire beforehand.

**Comment by HEnquist** [comment]
Hi, I was not aware of this functionality (I have not needed it), so no plans. I would be happy to accept a PR for adding support for it.
Looking at the example, it seems like the initialisation is very different, but once you have the AudioClient things work the same as normal capture. Correct?
A PR should ideally include a simple example.
