### ISSUE TITLE
Example outdated

### ISSUE THREAD

**Issue by MarijnKagchelland** [HEnquist/wasapi-rs#33]
In the example record_application.rs on line 30 is a function called on the "struct AudioClient" that is not implemented in the 0.14.0 (newest crate on crates.io at 12-june-2024) version. The function "AudioClient::new_application_loopback_client(process_id, include_tree)?". If I understand the code correctly, it gives the user a handle/hook to listen in to an applications audio endpoint/stream. I also do not see a method that is implemented in the 0.14.0 version that creates the capture. 

I tried to look in the implementation of AudioCaptureClient and AudioRenderClient and also did not find a way to get the audio stream/endpoint of applications. 

So my question is: How I get an application audiostream/endpoint with the 0.14.0 crate? I only need read access of the applications streams.

**Comment by HEnquist** [comment]
The code in the master branch is the next version, that I will release as 0.15 as soon as I have a little time. The application loopback capture is a new feature, it's not available in 0.14.

**Comment by MarijnKagchelland** [comment]
Aah ty, Good luck and happy programming
